/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.todoservices.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Todo service. Represents a row in the &quot;Todo_Todo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.todoservices.model.impl.TodoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.todoservices.model.impl.TodoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Todo
 * @generated
 */
@ProviderType
public interface TodoModel extends BaseModel<Todo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a todo model instance should use the {@link Todo} interface instead.
	 */

	/**
	 * Returns the primary key of this todo.
	 *
	 * @return the primary key of this todo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this todo.
	 *
	 * @param primaryKey the primary key of this todo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this todo.
	 *
	 * @return the ID of this todo
	 */
	public long getId();

	/**
	 * Sets the ID of this todo.
	 *
	 * @param id the ID of this todo
	 */
	public void setId(long id);

	/**
	 * Returns the name of this todo.
	 *
	 * @return the name of this todo
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this todo.
	 *
	 * @param name the name of this todo
	 */
	public void setName(String name);

	/**
	 * Returns the done of this todo.
	 *
	 * @return the done of this todo
	 */
	public boolean getDone();

	/**
	 * Returns <code>true</code> if this todo is done.
	 *
	 * @return <code>true</code> if this todo is done; <code>false</code> otherwise
	 */
	public boolean isDone();

	/**
	 * Sets whether this todo is done.
	 *
	 * @param done the done of this todo
	 */
	public void setDone(boolean done);

	/**
	 * Returns the due date of this todo.
	 *
	 * @return the due date of this todo
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this todo.
	 *
	 * @param dueDate the due date of this todo
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the user of this todo.
	 *
	 * @return the user of this todo
	 */
	public long getUser();

	/**
	 * Sets the user of this todo.
	 *
	 * @param user the user of this todo
	 */
	public void setUser(long user);

}